# cloudbuild.yaml
# Optimized and simplified GCP Cloud Build configuration for Next.js deployment to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    env: ['DOCKER_BUILDKIT=1']
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '.' # Docker context
      - '-f'
      - 'Dockerfile'
      # Pass ONLY PUBLIC substitutions as build arguments to the Dockerfile
      # Redis connection details are NOT needed at build time
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_TOKEN=${_NEXT_PUBLIC_API_TOKEN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_ID=${_NEXT_PUBLIC_SITE_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_NAME=${_NEXT_PUBLIC_SITE_NAME}'
      - '--build-arg'
      - 'NEXT_PUBLIC_HOSTNAME=${_NEXT_PUBLIC_HOSTNAME}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}'
      - '--build-arg'
      - 'NEXT_LANG=${_NEXT_LANG}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MEILISEARCH_HOST=${_NEXT_PUBLIC_MEILISEARCH_HOST}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY=${_NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MEILISEARCH_INDEX_NAME=${_NEXT_PUBLIC_MEILISEARCH_INDEX_NAME}'
      - '--build-arg'
      - 'NEXT_PUBLIC_IMAGE_URL=${_NEXT_PUBLIC_IMAGE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_IMAGE_BUCKET=${_NEXT_PUBLIC_IMAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GAMES_API_URL=${_NEXT_PUBLIC_GAMES_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GAMES_API_TOKEN=${_NEXT_PUBLIC_GAMES_API_TOKEN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_PATH=${_NEXT_PUBLIC_BASE_PATH}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SWETRIX_PROJECT_ID=${_NEXT_PUBLIC_SWETRIX_PROJECT_ID}'
  
  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      # --- VPC Connector Configuration ---
      - '--vpc-connector'
      - '${_VPC_CONNECTOR}'
      - '--vpc-egress'
      - 'private-ranges-only' # Or 'all-traffic' depending on your needs
      # --- Environment Variables ---
      - '--set-env-vars'
      - |- # Use |- for multi-line string
        NODE_ENV=production,
        NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL},
        NEXT_PUBLIC_API_TOKEN=${_NEXT_PUBLIC_API_TOKEN},
        NEXT_PUBLIC_SITE_ID=${_NEXT_PUBLIC_SITE_ID},
        NEXT_PUBLIC_SITE_NAME=${_NEXT_PUBLIC_SITE_NAME},
        NEXT_PUBLIC_HOSTNAME=${_NEXT_PUBLIC_HOSTNAME},
        NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL},
        NEXT_LANG=${_NEXT_LANG},
        NEXT_PUBLIC_MEILISEARCH_HOST=${_NEXT_PUBLIC_MEILISEARCH_HOST},
        NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY=${_NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY},
        NEXT_PUBLIC_MEILISEARCH_INDEX_NAME=${_NEXT_PUBLIC_MEILISEARCH_INDEX_NAME},
        NEXT_PUBLIC_IMAGE_URL=${_NEXT_PUBLIC_IMAGE_URL},
        NEXT_PUBLIC_IMAGE_BUCKET=${_NEXT_PUBLIC_IMAGE_BUCKET},
        NEXT_PUBLIC_GAMES_API_URL=${_NEXT_PUBLIC_GAMES_API_URL},
        NEXT_PUBLIC_GAMES_API_TOKEN=${_NEXT_PUBLIC_GAMES_API_TOKEN},
        REDIS_HOST=${_REDIS_HOST},
        REDIS_PORT=${_REDIS_PORT},
        REDIS_PASSWORD=${_REDIS_PASSWORD},
        NEXT_PUBLIC_BASE_PATH=${_NEXT_PUBLIC_BASE_PATH},
        NEXT_PUBLIC_SWETRIX_PROJECT_ID=${_NEXT_PUBLIC_SWETRIX_PROJECT_ID}

# List of images built by this pipeline
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'

# Default substitution values.
# Override these in your Cloud Build trigger configuration.
substitutions:
  _SERVICE_NAME: 'gds-optimised'
  _REGION: 'europe-west8'
  _ARTIFACT_REGISTRY_REPO: 'nextjs-apps' # Your Artifact Registry repository name
  _VPC_CONNECTOR: 'projects/${PROJECT_ID}/locations/${_REGION}/connectors/redis-connector' # Fully qualified name

  # --- Application Environment Variables ---
  _NEXT_PUBLIC_API_URL: 'http://your-api.example.com'
  _NEXT_PUBLIC_API_TOKEN: 'your_api_token'
  _NEXT_PUBLIC_SITE_ID: 'gds'
  _NEXT_PUBLIC_SITE_NAME: 'Production Site'
  _NEXT_PUBLIC_HOSTNAME: 'www.example.com'
  _NEXT_LANG: 'en'
  _NEXT_PUBLIC_MEILISEARCH_HOST: 'http://your-meili.example.com'
  _NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY: 'your_meili_search_key'
  _NEXT_PUBLIC_MEILISEARCH_INDEX_NAME: 'your_meili_index'
  _NEXT_PUBLIC_IMAGE_URL: 'http://images.example.com'
  _NEXT_PUBLIC_IMAGE_BUCKET: 'your-image-bucket-name'
  _NEXT_PUBLIC_GAMES_API_URL: 'https://games.example.com'
  _NEXT_PUBLIC_GAMES_API_TOKEN: 'your_games_api_token'
  _NEXT_PUBLIC_SITE_URL: 'https://www.example.com'
  _NEXT_PUBLIC_BASE_PATH: '/it'
  _NEXT_PUBLIC_SWETRIX_PROJECT_ID: 'your_swetrix_project_id'
  
  # --- Secret/VPC substitutions (Best to configure in trigger) ---
  _REDIS_HOST: '10.0.0.3'
  _REDIS_PORT: '6379'
  _REDIS_PASSWORD: 'your-redis-auth-string'


options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true

timeout: '1200s'